### ISSUE TITLE
Public volumes not displayed

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#118]
Public volumes "Hippocampus" and "UFO" appear in the list of incoming volumes but are not displayed when selected.

**Comment by JThoennissen** [comment]
**Private** volumes are also not displayed. They can be uploaded but don't appear in the viewer.

**Comment by pacher** [comment]
@xgui3783 Can you please have a look?
From what I see the problem is not with the backend but in voluba itself. 
Voluba retrieves info json but does not request any chunks.
Public and private volumes can be displayed without problems using vanilla neuroglancer.

**Comment by xgui3783** [comment]
from console, it seems the image service backend is no longer providing
voxel_offset property?

compare: `
https://neuroglancer.humanbrainproject.org/precomputed/JuBrain/v2.2c/colin27_seg/info`
vs `
https://zam10143.zam.kfa-juelich.de/chumni/nifti/public/UFO_Unknown_Functional_Observation/info`
?
