### ISSUE TITLE
Deletion of a single landmark pair is faulty

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#119]
1. When deleting a pair of landmarks they are removed from the landmark list but still appear in the viewer.
2. When adding a new landmark pair after deleting one the new entry consists of the removed BigBrain landmark paired with the newly set landmark in the incoming volume. The following landmarks are then set accordingly.

example: B = BigBrain landmark, I = incoming volume landmark
set B1, I1 
set B2, I2
delete B2, I2
set B3, I3 --> results in pair B2, I3
set B4, I4 --> results in pair B3, I4

For better understanding I added a video:
https://user-images.githubusercontent.com/32842931/175962784-b5401271-e2c0-4943-a2be-98cc9f02310c.mp4

**Comment by fsdavid** [comment]
Demo: https://voluba-fix-removing.apps-dev.hbp.eu/#/
PR: https://github.com/FZJ-INM1-BDA/voluba/pull/153
