### ISSUE TITLE
Sliders in two pane mode

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#120]
Having the opacity/contrast/brightness slider in the two pane mode would be useful to make significant structures visible for easier landmark positioning.

**Comment by fsdavid** [comment]
Needs to use `ng layer tune` twice. It will work without issues.

**Comment by fsdavid** [comment]
Currently, `ng-layer-tune` does not support custom views

**Comment by fsdavid** [comment]
PR is here: https://github.com/FZJ-INM1-BDA/voluba/pull/162
It's waiting to new version of ng_layer_tune
