### ISSUE TITLE
Add RGB support

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#124]
In the current version, datasets are only displayed as grayscale images even if the data is RGB. Support for this should be added to be able to extract all possible information from the data (e.g. marked components in two photon fluorescence microscopy images).

**Comment by xgui3783** [comment]
should be fixed by https://github.com/FZJ-INM1-BDA/voluba/pull/131 

pending https://github.com/FZJ-INM1-BDA/voluba/pull/130 to be merged into main
