### ISSUE TITLE
[feature] allow user to enter voxel resolution (alternative to scaling)

### ISSUE THREAD

**Issue by xgui3783** [FZJ-INM1-BDA/voluba#133]
if the user knows voxel resolution, they should be able to enter it (instead of scaling)

(edit: from internal meeting 2022-09-12)

**Comment by fsdavid** [comment]
@xgui3783 Is there any way to set a specific resolution on `neuroglancer`?

**Comment by xgui3783** [comment]
Voxel resolution.

Not specifically, but it can be calculated, and applied to the affine.

**Comment by fsdavid** [comment]
@xgui3783 Thanks. So we have to get the current resolution and calculate the scale with new values?

**Comment by xgui3783** [comment]
We can get native voxel resolution from /info (unless voluba image service provide it)

**Comment by fsdavid** [comment]
Demo: https://custom-resol.apps-dev.hbp.eu/#/
