### ISSUE TITLE
Private volume lost when changing parcellation in siibra-explorer

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#142]
When viewing the anchoring result in siibra-explorer via VoluBA, the aligned volume is displayed on top of BigBrain space and BigBrain Isocortex parcellation. Chaning the parcellation leads to the user volume disappearing. As long as the parcellation is supported by BigBrain, the volume should be shown as e.g. comparing the alinged volume to cytoarchitectonic maps is the most interesting for the user.

**Comment by fsdavid** [comment]
This is the Siibra Explorer issue. Ref: https://github.com/FZJ-INM1-BDA/siibra-explorer/issues/1285

**Comment by fsdavid** [comment]
I will close the issue here if there are no more comments.

**Comment by fsdavid** [comment]
Needs to update Voluba plugin

**Comment by fsdavid** [comment]
Demo: https://voluba-next.apps-dev.hbp.eu/
