### ISSUE TITLE
Resolution/Scale reset after selection of transform dialog

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#166]
The issue causes two problems:

1. When selecting Hippocampus public volume it is displayed too big. By clicking on the brain icon to transform it, the volume is rescaled correctly but due to this moved outside of the reference space.
2. When a user sets the resolution/scale, closes the transform dialog and opens it again, the resolution/scale is reset to the initial scaling that is retrieved from the precomputed info file.

**Comment by JThoennissen** [comment]
Find a screencast showing 1. below:

https://user-images.githubusercontent.com/32842931/231501995-f66aa0ec-f7d3-43d8-b0cc-d8c7dccae8fd.mp4

**Comment by xgui3783** [comment]
merged and deployed to staging , can you check if it's fixed?

https://voluba-staging.apps.hbp.eu/#/

**Comment by JThoennissen** [comment]
The second issue is fixed 👍 
The first issue remains, but is not urgent. It seems the scale is initially set to 20,53 for Hippocampus volume ...

**Comment by xgui3783** [comment]
Here, I am respecting the transform returned by the image service. 

I am unsure why the image service returned to contain the specific transform. better asking @pacher 

Why the Hippocampus public volume has a transform like that

```json
[
  [
    20.531328320802004,
    0,
    0,
    -24353.02734375
  ],
  [
    0,
    20.531328320802004,
    0,
    -24353.02734375
  ],
  [
    0,
    0,
    16.66734486266531,
    -29998.779296875
  ],
  [
    0,
    0,
    0,
    1
  ]
]
```

A command line to retrieve the transform would be

```bash
curl 'https://zam10143.zam.kfa-juelich.de/chumni/list' | jq '.[1].extra.neuroglancer'
```

**Comment by pacher** [comment]
It seems that affine matrix stored in Hippocampus nifti is wrong which is not surprising given the origin of this nifti.
I would suggest to close the issue and re-open if this problem is observed with any other user uploaded nifti generated by any standard software.
