### ISSUE TITLE
Change naming of rodent reference volumes

### ISSUE THREAD

**Issue by JThoennissen** [FZJ-INM1-BDA/voluba#180]
Maja wrote:

Could I ask you to change the naming of reference spaces for the mouse and rat atlases in the UI and the documentation?
-	The official name is Waxholm atlas of the Sprague Dawley rat. You could use WHS-SD atlas if you want as a shorter acronym.
-	The latest version of the brain regions delineations are v4 for the rat (https://doi.org/10.21203/rs.3.rs-2466303/v1) , the peer reviewed publication will be published very soon.
-	The latest version of the brain regions delineations for the Allen mouse atlas are from 2017. We usually write CCFv3_2017. The reference to the publication is correct.

@xgui3783 Could you please change this in the UI? Thanks!

**Comment by xgui3783** [comment]
fixed by #182
