### ISSUE TITLE
[bug] "{Lower,Higher} threshold" values get rounded to 2 decimals when switching panes

### ISSUE THREAD

**Issue by chourroutm** [FZJ-INM1-BDA/voluba#197]
I have spotted a bug in the voluba staging version: when one changes the focus from the voluba window to siibra, the numbers for the windowing get rounded to 2 decimals, which is critical for the display of 16-bit data with narrow histograms, cf. attached screenshot.

![Screenshot 2024-12-10 at 12-16-54 Siibra Explorer _ edited](https://github.com/user-attachments/assets/87f2bf17-cc78-447e-bdc3-787c3a9e7193)

The data in the screenshot is not released yet, thus I can only share the link by email. The adequate window is from 0.219 to 0.221.

**Comment by xgui3783** [comment]
@chourroutm can you check again? (link I believe is [link](https://atlases.ebrains.eu/viewer-staging/#/a:juelich:iav:atlas:v1.0.0:1/t:minds:core:referencespace:v1.0.0:a1655b99-82f1-420f-a3c2-fe80fd4c8588/p:juelich:iav:atlas:v1.0.0:4/@:0.0.0.-W000.._eCwg.2-FUe3._-s_W.2_evlu..DMVW..nqCS.dBHS.1Mukg..pq_/x-overlay-layer:zarr:%2F%2Fgs:%2F%2Fucl-hip-ct-ebb-hseid5pvpp8vgtzt%2Fsub-01%2Fses-01%2Fmicr%2Fsub-01_ses-01_sample-brain_XPCT.ome.zarr) )

I entered `0.2188` as lower threshold and `0.2211` as upper threshold. on collapsing/uncollapsing the panel, the threshold seems to be holding. 

At the moment, we increased decimal round off from 2 to 4.

**Comment by xgui3783** [comment]
@chourroutm can you check again? (link I believe you have, and redacted)

I entered 0.2188 as lower threshold and 0.2211 as upper threshold. on collapsing/uncollapsing the panel, the threshold seems to be holding.

At the moment, we increased decimal round off from 2 to 4.

**Comment by chourroutm** [comment]
It works well, thank you!
