### ISSUE TITLE
Missing option for choosing the transformation type

### ISSUE THREAD

**Issue by ylep** [FZJ-INM1-BDA/voluba#31]
Voluba should allow the user to choose the transformation type to estimate, like the old landmark-reg did. Choices should be:

- Rigid: `rigid+reflection`
- Similarity: `similarity+reflection`
- Rigid (forbid mirror): `rigid`
- Similarity (forbid mirror): `similarity`
- Affine: `affine` (this one is experimental, because Neuroglancer may not handle skewed transforms very well, at least it did not when I implemented the old landmark-reg)

**Comment by JThoennissen** [comment]
close
