### ISSUE TITLE
Applying transformations to landmarks does not work

### ISSUE THREAD

**Issue by SBludau** [FZJ-INM1-BDA/voluba#98]
I I visually overlaid a structure and then clicked landmark pairs. However, the button "Compute and display transform based on landmarks" has no function.
I used the staging version you send via mail.

**Comment by xgui3783** [comment]
@SBludau can you export the landmark pairs via:

`Save Result` (left column) > `Save Transformation as JSON` and attach the JSON file here please?

**Comment by xgui3783** [comment]
hmm, actually, I can reproduce. 

I will issue a fix ASAP

**Comment by SBludau** [comment]
Sure.


[BigBrain_WinterSchool_transformMatrix_Landmark-pairs.zip](https://github.com/FZJ-INM1-BDA/voluba/files/5786690/BigBrain_WinterSchool_transformMatrix_Landmark-pairs.zip)

**Comment by xgui3783** [comment]
@SBludau I have made some changes, and it should fix the issue. Can you let me know if the issue has been resolved?

**Comment by SBludau** [comment]
Thank you very much!
Application of the transformations and the later presentation in IAV seems to work fine now.

**Comment by xgui3783** [comment]
Should be fixed.

Root cause was incorrect linear backend endpoint
